### ISSUE TITLE
1.3 incompatible

### ISSUE THREAD

**Issue by KlyithSA** [janxious/InternalHeaters#5] opened 2019-01-18 17:24 UTC
Breaks the SP mech bay and the mission loading screen. Skirmish mech bay does endless loading.

MissingMethodException: Method not found: 'BattleTech.CombatGameConstants.CreateFromSaved'.
at (wrapper dynamic-method) BattleTech.MechStatisticsRules.CalculateHeatEfficiencyStat_Patch1 (BattleTech.MechDef,single&,single&) <0x001b0>
at BattleTech.UI.MechLabStatBlockWidget.SetHeatEfficiencyStat (BattleTech.UI.LanceStatGraphic,BattleTech.MechDef,BattleTech.UI.MechLabStatBlockWidget/StatisticValidationFunction) <0x00083>
at BattleTech.UI.MechLabStatBlockWidget.SetData (BattleTech.MechDef) <0x004a2>
at BattleTech.UI.MechLabPanel.LoadMech (BattleTech.MechDef) <0x004ac>
at BattleTech.UI.MechLabPanel.OnRequestResourcesComplete () <0x0005a>
at BattleTech.UI.MechLabPanel/c__Iterator0.MoveNext () <0x00947>
at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator,intptr) <0x00058>

**Comment by janxious** [comment] 2019-01-18 17:25
Duplicate of https://github.com/BattletechModders/InternalHeaters/issues/4

I don't have time to update this right now.

**Closed as completed by janxious** 2019-01-18 17:25 UTC
